TaskTwo/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TaskTwo.Models
{
    public class Order
    {
        public int Id {get; set; }
        

        public DateTime DatePurchase { get; set; }

        public string UserId { get; set; }
        public User User { get; set; }

        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public Order()
        {
            ProductOrders = new List<ProductOrder>();
        }

    }
}

TaskTwo/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

namespace TaskTwo.Models
{
    [Serializable]
    public class Product
    {
        [XmlIgnore]
        public int Id {get;set;}
        [Display(Name ="Name")]
        [Required(ErrorMessage = "Product name is required")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Product price is required")]
        public int Price { get; set; }
        [Required(ErrorMessage = "Product describtion is required")]
        public string Describe { get; set; }

        [XmlIgnore]
        public DateTime DateUpd { get; set; }

        [XmlIgnore]
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public Product()
        {
            ProductOrders = new List<ProductOrder>();
            
        }
    }
}

TaskTwo/Models/User.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Threading.Tasks;
using TaskTwo.Models;

namespace TaskTwo.Models
{
    public class User : IdentityUser
    {
        public string Name { get; internal set; }
        public string Surname { get; set; }
        public DateTime DateRegister { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public User()
        {
            Orders = new List<Order>();
        }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);

            // Add custom user claims here
            return userIdentity;
        }

    }

    public class RegisterModel
    {
        [Required(ErrorMessage = "User name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "User surname is required")]
        public string Surname { get; set; }
        public DateTime DateRegister { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "User password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

TaskTwo/Controllers/CreatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;

namespace TaskTwo.Controllers
{
    public class CreatingController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        // GET: Creating
        [Authorize]
        public ActionResult Index()
        {
            System.Diagnostics.Debug.WriteLine(User.Identity.Name);
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateProduct(Product product)
        {
            product.DateUpd = DateTime.Now;

            using (ApplicationContext db = new ApplicationContext())
            {
                if (ModelState.IsValid)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    ViewBag.Status = "Added product";
                    return View("Index");
                }
                else
                {
                    ViewBag.Status = "Error";
                    return View("Index");
                }

            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreateOrder(string id)
        {
            
            using (ApplicationContext db = new ApplicationContext())
            {
                List<Product> allProducts = db.Products.ToList();
                ViewData["userId"] = id;
                ViewData["products"] = allProducts;
                return View();
            }

        }

        [Authorize]
        [HttpPost]
        public ActionResult CreateOrder()
        {

            string userId = User.Identity.GetUserId();

            string s = Request["checkProduct"];
            int[] prod_id = s.Split(',').Select(t => Convert.ToInt32(t)).ToArray();

            Order order = new Order() { UserId = userId, DatePurchase = DateTime.Now } ;
            

            
                try
                {
                    using (ApplicationContext db = new ApplicationContext())
                    {
                    order.User = db.Users.Where(t => t.Id == userId).First();

                        for (int i = 0; i < prod_id.Length; ++i)
                        {
                            var id = prod_id[i];
                            ProductOrder po = new ProductOrder();
                            po.ProductId = prod_id[i];
                            order.ProductOrders.Add(po);
                        }

                        db.Orders.Add(order);
                        db.SaveChanges();

                        

                        ViewBag.Status = "Order added";
                        
                    }
                return RedirectToAction("Index", "Details");
            }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                }
                return View("Error");
            
        }
    }
}

TaskTwo/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;
using Microsoft.AspNet.Identity;

namespace TaskTwo.Controllers
{
    public class DetailsController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            try
            {
                string _id = User.Identity.GetUserId();
                using (ApplicationContext db = new ApplicationContext())
                {
                    System.Diagnostics.Debug.WriteLine(_id);
                    var user = db.Users.Where(t => t.Id == _id).First();
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            return View("Error");
        }

        [Authorize]
        public ActionResult Products()
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                var products = db.Products.ToList();
                return View(products);
            }
        }

        [Authorize]
        public ActionResult Orders()
        {
            string userId = User.Identity.GetUserId();
            using (ApplicationContext db = new ApplicationContext())
            {
                var orders = db.Orders.Where(t => t.UserId == userId).ToList();

                List<OrderInfo> userInfoList = new List<OrderInfo>();

                var productOrders = db.Products.Join(
                    db.ProductOrders,
                    p => p.Id,
                    po => po.ProductId,
                    (p, po) => new
                    {
                        OrderId = po.OrderId,
                        ProductName = p.ProductName
                    });

                foreach(var item in orders)
                {
                    var result = productOrders.Where(l => l.OrderId == item.Id).Select(l => l.ProductName).ToList();
                    OrderInfo orderInfo = new OrderInfo() { OrderId = item.Id };
                    orderInfo.ProductNames.AddRange(result);

                    userInfoList.Add(orderInfo);
                }

                return View(userInfoList);
            }
        }


        //public ActionResult PurchasingInfo()
        //{
        //    string userId = User.Identity.GetUserId();

        //    using (ApplicationContext db = new ApplicationContext())
        //    {
        //        var productOrders = db.Products.Join(
        //            db.ProductOrders,
        //            p => p.Id,
        //            po => po.ProductId,
        //            (p, po) => new
        //            {
        //                OrderId = po.OrderId,
        //                ProductName = p.ProductName,
        //                Spent = 
        //            });

        //        return View();
        //    }
        //}
    }
}

TaskTwo/Controllers/EditingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TaskTwo.Models;
using Microsoft.AspNet.Identity;

namespace TaskTwo.Controllers
{
    public class EditingController : Controller
    {
        // GET: Editing
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditingUser()
        {
            string userId = User.Identity.GetUserId();
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    if (string.IsNullOrEmpty(userId)) throw new Exception("ser ID is null ");
                    User user = db.Users.Single(t => t.Id == userId);
                    return View(user);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }

        }

        [HttpGet]
        [Authorize]
        public ActionResult EditingProduct(int id)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    if (id == 0) throw new Exception("User ID is null");
                    Product product = db.Products.Single(t => t.Id == id);
                    return View(product);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditingOrder(int id = 0)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    if (id == 0) throw new Exception("Product ID is null");
                    Order order = db.Orders.Single(t => t.Id == id);
                    return View(order);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }
        }


        [HttpPost]
        [Authorize]
        public ActionResult UpdUser(User user)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine($"{user.Id} {user.Name}");
                    db.Users.Attach(user);
                    db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.Status = "Edited";
                    return RedirectToAction("Users", "Details");
                }

                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdProduct(Product product)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine($"{product.Id} {product.ProductName}");
                    db.Products.Attach(product);
                    db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.Status = "Edited";
                    return Redirect("../Details/Products");
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdOrder(User user)
        {
            using (ApplicationContext db = new ApplicationContext())
            {
                try
                {
                    System.Diagnostics.Debug.WriteLine($"{user.Id} {user.Name}");
                    db.Users.Attach(user);
                    db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.Status = "Edited";
                    return View("~/Views/Details/Orders.aspx");
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                    ViewBag.Error = ex.Message;
                    return View("Error");
                }

            }
        }
    }
}

TaskTwo/Views/Details/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="~/Content/ForDiv.css" type="text/css" />

<div class="row">
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("My account", "Users", "Details")</h2>
    </div>
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("Products", "Products", "Details")</h2>
    </div>
    <div class="col-lg-4" id="ref">
        <h2>@Html.ActionLink("Orders", "Orders", "Details")</h2>
    </div>
</div>

TaskTwo/Views/Details/Orders.cshtml
@model IEnumerable<TaskTwo.Models.OrderInfo>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders of @User.Identity.Name</h2>

<p>
    @Html.ActionLink("Create New", "Index", "Creating")
</p>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductNames)
        </th>
        <th></th>
    </tr>

@foreach (var order in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => order.OrderId)
        </td>
        <td>
            @foreach (var product in order.ProductNames)
            {
                <ul>
                    <li>@product</li>
                </ul>
            }
        </td>
    </tr>
}

</table>

TaskTwo/Views/Details/Products.cshtml
@model IEnumerable<TaskTwo.Models.Product>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

<p>
    @Html.ActionLink("Create New", "Index", "Creating")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Describe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateUpd)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Describe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateUpd)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditingProduct", "Editing", new { id = item.Id }, null)
        </td>
    </tr>
}

</table>

TaskTwo/Views/Details/Users.cshtml
@model TaskTwo.Models.User

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRegister)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRegister)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditingUser", "Editing") |
    @Html.ActionLink("Back to List", "Index")
</p>